---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frontends.doslab.io
spec:
  group: doslab.io
  names:
    kind: Frontend
    plural: frontends
    shortNames:
      - frontend
    singular: frontend
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
