kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: test
  namespace: default
  labels:
    app: test
  annotations:
    kubesphere.io/creator: admin
spec:
  schedule: 0 0 * * *
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      template:
        metadata:
          creationTimestamp: null
          annotations:
            kubesphere.io/imagepullsecrets: '{}'
        spec:
          containers:
            - name: container-bz3y66
              image: 'nginx:1'
              ports:
                - name: http-0
                  containerPort: 80
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: default
          serviceAccount: default
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
