{
  "apiVersion": "doslab.io/v1",
  "kind": "Frontend",
  "metadata": {
    "name": "apps.deployment-table"
  },
  "spec": {
    "data": [
      {
        "title": "名称",
        "fixed": "left",
        "width": "500px",
        "kind": "link",
        "row": "metadata.name"
      },
      {
        "title": "就绪状态下的pod数",
        "width": "200px",
        "row": "spec.replicas"
      },
      {
        "title": "项目",
        "width": "300px",
        "row": "metadata.namespace"
      },
      {
        "title": "创建时间",
        "width": "200px",
        "row": "metadata.creationTimestamp"
      },
      {
        "kind": "action",
        "fixed": "right",
        "width": "100px",
        "title": "操作",
        "actionLink": [
          {
            "label": "编辑",
            "action": "UPDATE"
          },
          {
            "label": "删除",
            "action": "DELETE"
          }
        ]
      }
    ],
    "type": "table"
  }
}

